source 'http://rubygems.org'

gem "rails"
gem 'sqlite3'
gem "nifty-generators"
gem "gmaps4rails", :path => "../../"
gem 'ruby-debug'

group :test do
	gem 'rspec-rails'
  gem 'capybara', :git => 'git://github.com/jnicklas/capybara.git'
	gem 'database_cleaner'
	gem 'launchy'
	gem 'factory_girl_rails' 
end