source 'http://rubygems.org'

gem 'rails', '3.0.7'

gem 'sqlite3'

# gem 'capistrano'

gem 'ruby-debug'
gem 'jquery-rails'
gem 'devise'

gem 'refinerycms-base',       '~> 1.0.0'
gem 'refinerycms-core',       '~> 1.0.0'
gem 'refinerycms-dashboard',  '~> 1.0.0'
gem 'refinerycms-images',     '~> 1.0.0'
gem 'refinerycms-pages',      '~> 1.0.0'
gem 'refinerycms-resources',  '~> 1.0.0'
gem 'refinerycms-settings',   '~> 1.0.0'
gem 'refinerycms-i18n',       '~> 1.0.0'
group :development, :test do
  gem 'refinerycms-testing',  '~> 1.0.0'
end

group :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'jasmine'
  gem 'guard'
  gem 'guard-rspec'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'launchy'
  gem 'factory_girl_rails'
  gem "shoulda-matchers"
  gem 'selenium-webdriver', '2.5.0'
end
